(define (RLC R L C dt)
  (lambda (vC0 iL0)
    (define vC (integral (delay dvC) vC0 dt))
    (define iL (integral (delay diL) iL0 dt))
    (define dvC (scale-stream iL (- (/ 1.0 C))))
    (define diL (add-streams (scale-stream vC (/ 1.0 L))
                             (scale-stream iL (- (/ R L)))))
    (cons vC iL)))
